# config/config.yaml

data:
  data_dir: './data'
  batch_size: 64
  num_workers: 4
  val_split: 0.2
  random_seed: 42

model:
  model_name: 'google/vit-base-patch16-224-in21k'
  num_classes: 100
  learning_rate: 1e-4

trainer:
  max_epochs: 30
  gpus: 1  # Set to 0 if no GPU is available
  progress_bar_refresh_rate: 20

logging:
  project: 'Image_Classification_ViT'
  run_name: 'ViT_CIFAR100'
  log_model: 'all'
